### PR TITLE
Update DEPLOYMENT

### PR DESCRIPTION
**Pull request by henrikstranneheim**
### This PR adds | fixes:
- 

**How to prepare for test**:
- [ ] `ssh` to ...
- [ ] Install on stage:
`bash servers/resources/SERVER.scilifelab.se/update-[THIS_TOOL]-stage.sh [THIS-BRANCH-NAME]`

### How to test:
-

### Expected outcome:
- [ ]

### Review:
- [ ] Code approved by
- [ ] Tests executed by
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by northwestwitch — APPROVED** [review]
Looks good! 👍🏻

**Comment by northwestwitch** [comment]
Woops, it's not passing the tests, something connected with sambamba. I wonder since when!

**Comment by northwestwitch** [comment]
@henrikstranneheim I can help fixing the problem that makes tests fail, so we can merge this and #242

**Comment by henrikstranneheim** [comment]
@northwestwitch That sounds fantastic 🎖️

**Comment by northwestwitch** [comment]
```
Run brew install sambamba
Warning: No available formula with the name "sambamba". Did you mean samba?
==> Searching for similarly named formulae...
This similarly named formula was found:
samba
To install it, run:
  brew install samba
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
Error: Process completed with exit code 1.
```

That's weird, it was working on the other branch!

**Comment by northwestwitch** [comment]
Oh look, last week they have removed Sambamba from https://github.com/brewsci:

https://github.com/brewsci/homebrew-bio/commit/212f6116d58b8f79263c858f3b6b0bada0cd772e

**Comment by henrikstranneheim** [comment]
@northwestwitch Great! Thx for the help

**Pull request merged**
