### PR TITLE
added git lint to travis build

### PR DESCRIPTION
**Pull request by patrikgrenfeldt**
Automatically runs lint on the changed code (not all code).

# How to test:
1. go to the conversation tab in this PR on github
2. scroll down to "Checks"
3. Open the travis build details for the push and the merge 
4. view the build logs

# Expected outcome:
Both of the build logs (push & merge) should contain the line: `The command "git reset --soft ${TRAVIS_COMMIT_RANGE%...*} && git lint" exited with 0.`
and the builds should be successful

### CODE REVIEW

**Comment by ingkebil** [comment]
Any idea on how to fix the failing tests?

**Comment by patrikgrenfeldt** [comment]
I suggest that we compare the build logs of the current with any one of the last successful builds (e.g. https://travis-ci.org/Clinical-Genomics/chanjo/builds/445656631) to try to figure out what is different

**Comment by patrikgrenfeldt** [comment]
> Any idea on how to fix the failing tests?

Fixed!

**Comment by ingkebil** [comment]
Looking good! ship it :) :package: :rocket:

**Pull request merged**
