### PR TITLE
Github actions for pytest & coveralls and for building and pushing to Docker Hub

### PR DESCRIPTION
**Pull request by northwestwitch**
### This PR adds | fixes:
- Switch to Github actions for tests and coverage
- Added action to build the Docker image and pushing it to Docker Hub with 2 tags: "latest" and actual latest repo tag.

**How to prepare for test**:
- It's all automated but this needs fixing:
- [ ] DOCKER_USERNAME secret
- [ ] DOCKER_PASSWORD secret

### How to test:
- Just watch

### Expected outcome:
- [x] tests should pass

### Review:
- [ ] Code approved by
- [x] Tests executed by Github actions

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by northwestwitch** [comment]
Ready for review. An easy one!

**Comment by northwestwitch** [comment]
In order to push to Github actions I need to create the secrets and I need an admin.. @moonso? 😁

**Comment by moonso** [comment]
Nice @northwestwitch , I've added them on the organisational level. Not 100% how it works but please test

**Review by moonso — APPROVED** [review]
👍

**Comment by northwestwitch** [comment]
> Nice @northwestwitch , I've added them on the organisational level. Not 100% how it works but please test

Cool, thanks!

**Pull request merged**
