### PR TITLE
Docs stuff

### PR DESCRIPTION
**Pull request by moonso**
Small updates to documentation

### CODE REVIEW

**Comment by moonso** [comment]
Will you look at this @robinandeer ?

**Comment by robinandeer** [comment]
Great updates to documentation!

What are you doing more? Are you setting up the exon-gene connections in the init command?

**Comment by moonso** [comment]
Yes, and added some error handling when no database could be found. And skipping the bootstrap thing so the bed file is included in distribution

**Comment by patrikgrenfeldt** [comment]
@moonso It has been a while since this PR was created, what do you think should happen to it?

**Comment by moonso** [comment]
Wow I have no memory of this... I think we need someone that is responsible for Chanjo that understands the code to make a decision of what to do with this.

**Comment by moonso** [comment]
However it looks like is should be safe to merge it

**Comment by patrikgrenfeldt** [comment]
@moonso please resolve the conflicts

**Comment by moonso** [comment]
And then?

**Comment by patrikgrenfeldt** [comment]
Then I'd like to see you update the PR according to our development guideline http://www.clinicalgenomics.se/development/github/pr/ What do you think should be the then?

**Comment by moonso** [comment]
I mean that since no one is in control of chanjo I don't want to spend time on this if it's not leading anywhere

**Comment by ingkebil** [comment]
According to 1098:13, @moonso is the maintainer of this package with @patrikgrenfeldt as the deputy. Are you saying that information is incorrect and needs to be updated?

**Comment by patrikgrenfeldt** [comment]
@moonso merge this?

**Comment by moonso** [comment]
Sure go ahead!

**Comment by patrikgrenfeldt** [comment]
closing stale PR

**Pull request closed without merging**
